# Generated by Django 2.2.3 on 2019-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('signature', models.CharField(max_length=20, verbose_name='个性签名')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('is_actived', models.BooleanField(default=False, verbose_name='激活状态')),
                ('image_path', models.CharField(max_length=50, verbose_name='头像图片路径')),
                ('gender', models.CharField(default='male', max_length=10, verbose_name='性别')),
                ('browser_list', models.CharField(default='[]', max_length=300, verbose_name='浏览')),
                ('browser_number', models.IntegerField(default=0, verbose_name='浏览量')),
                ('have_watched', models.CharField(default='[]', max_length=300, verbose_name='观看')),
                ('watch_number', models.IntegerField(default=0, verbose_name='观看量')),
                ('collection_list', models.CharField(default='[]', max_length=300, verbose_name='收藏')),
                ('collect_number', models.IntegerField(default=0, verbose_name='收藏量')),
                ('prefer_actors', models.CharField(default='[]', max_length=300, verbose_name='偏爱演员')),
                ('prefer_directors', models.CharField(default='[]', max_length=300, verbose_name='偏爱的导演')),
                ('recommend_movies', models.CharField(default='[]', max_length=300, verbose_name='推荐的电影列表')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
