# Generated by Django 2.2.3 on 2020-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('signature', models.CharField(blank=True, max_length=20, null=True, verbose_name='个性签名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='用户邮箱')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=10, null=True, verbose_name='性别')),
            ],
        ),
    ]
