# Generated by Django 2.2.3 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户职业'),
        ),
    ]
