# Generated by Django 2.2.3 on 2019-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='browser_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='browser_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(null=True, upload_to='UserAvatar/', verbose_name='头像图片路径'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_actived',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
    ]
