# Generated by Django 2.2.3 on 2020-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200427_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.AddField(
            model_name='user',
            name='user_ageSec',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户年龄区间'),
        ),
    ]
