# Generated by Django 3.0.2 on 2020-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20191005_1820'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='collect_number',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='collection_list',
        # ),
    ]
