# Generated by Django 2.2.3 on 2020-05-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20200414_1456'),
        ('Users', '0003_auto_20200428_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collected_movie',
            field=models.ManyToManyField(to='Movies.Movie'),
        ),
    ]
