# Generated by Django 3.0.2 on 2020-01-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200118_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collect_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='collection_list',
        ),
    ]
