# Generated by Django 3.0.2 on 2020-02-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200131_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommend_movies',
        ),
    ]
