# Generated by Django 2.2.3 on 2020-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20200414_1456'),
        ('Rating', '0001_initial'),
        ('Users', '0004_user_collected_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated_movie',
            field=models.ManyToManyField(related_name='rated_by_user', through='Rating.Rating', to='Movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='collected_movie',
            field=models.ManyToManyField(related_name='collected_by_user', to='Movies.Movie'),
        ),
    ]
