# Generated by Django 2.2.3 on 2020-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_user_recommend_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='have_watched',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_actived',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prefer_actors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prefer_directors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watch_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
