# Generated by Django 3.0.2 on 2020-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_remove_user_recommend_movies'),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recommend_id', models.AutoField(primary_key=True, serialize=False, verbose_name='推荐列表的id')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
