# Generated by Django 2.2.3 on 2020-04-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='update_time',
        ),
    ]
