# Generated by Django 3.0.2 on 2020-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('celebrity_id', models.AutoField(primary_key=True, serialize=False, verbose_name='明星id')),
                ('celebrity_name', models.CharField(max_length=20, unique=True, verbose_name='明星名字')),
                ('celebrity_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, null=True, verbose_name='明星性别')),
                ('celebrity_cover', models.ImageField(null=True, upload_to='CelebrityCover/%Y%m%d', verbose_name='明星封面图片路径')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
