# Generated by Django 2.2.3 on 2020-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmmakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='celebrity_doubanID',
            field=models.IntegerField(blank=True, null=True, verbose_name='豆瓣id'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='celebrity_cover',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='明星封面图片路径'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='celebrity_gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=10, null=True, verbose_name='明星性别'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='celebrity_name',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='明星名字'),
        ),
    ]
