# Generated by Django 2.2.3 on 2020-04-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False, verbose_name='rating id')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('timestamp', models.IntegerField(blank=True, default=0, null=True, verbose_name='时间戳')),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
    ]
