# Generated by Django 2.2.3 on 2020-03-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ratingID', models.AutoField(primary_key=True, serialize=False, verbose_name='rating id')),
                ('userID', models.IntegerField(default=0, verbose_name='用户ID')),
                ('movieID', models.IntegerField(default=0, verbose_name='电影ID')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('timestamp', models.IntegerField(default=0, verbose_name='时间戳')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
