# Generated by Django 2.2.3 on 2020-03-30 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movieID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
