# Generated by Django 2.2.3 on 2020-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0002_auto_20200330_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='时间戳'),
        ),
    ]
