# Generated by Django 3.0.2 on 2020-01-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0004_auto_20200131_1829'),
        ('Movies', '0004_movie_movie_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('agree_number', models.IntegerField(default=0, verbose_name='赞同量')),
                ('disagree_number', models.IntegerField(default=0, verbose_name='踩')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
