# Generated by Django 2.2.3 on 2020-04-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20200227_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='update_time',
        ),
    ]
