# Generated by Django 2.2.3 on 2019-10-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0003_auto_20191004_1442'),
        ('Users', '0002_auto_20191005_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowsingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
