# Generated by Django 3.0.2 on 2020-02-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户浏览记录id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
