# Generated by Django 3.0.2 on 2020-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_remove_user_recommend_movies'),
        ('History', '0001_initial'),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsehistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
