# Generated by Django 3.0.2 on 2020-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBrowsingHistory',
        ),
    ]
