# Generated by Django 2.2.3 on 2020-04-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0002_auto_20200227_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsehistory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='browsehistory',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='browsehistory',
            name='update_time',
        ),
    ]
