# Generated by Django 3.0.2 on 2020-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Filmmakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('movie_id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影id')),
                ('movie_name', models.CharField(max_length=100, unique=True, verbose_name='电影片名')),
                ('movie_length', models.IntegerField(default=0, verbose_name='电影片长')),
                ('movie_releaseTime', models.DateField(verbose_name='上映时间')),
                ('movie_showPos', models.CharField(default='中国大陆', max_length=10, verbose_name='上映地区')),
                ('movie_intro', models.CharField(max_length=512, null=True, verbose_name='剧情简介')),
                ('movie_cover', models.ImageField(null=True, upload_to='MovieCover/%Y%m%d', verbose_name='电影封面图片路径')),
                ('movie_grades', models.FloatField(default=0.0, verbose_name='豆瓣评分')),
                ('movie_alias', models.CharField(max_length=100, null=True, verbose_name='电影别名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影类别id')),
                ('category_name', models.CharField(max_length=10, unique=True, verbose_name='电影类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影标签id')),
                ('lab_content', models.CharField(max_length=10, verbose_name='电影标签内容')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', '导演'), ('actor', '演员')], max_length=15, verbose_name='在电影中的角色')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmmakers.Celebrity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='lab',
            field=models.ManyToManyField(to='Movies.MovieLab'),
        ),
        migrations.AddField(
            model_name='movie',
            name='roles',
            field=models.ManyToManyField(through='Movies.RoleTable', to='Filmmakers.Celebrity'),
        ),
    ]
