# Generated by Django 2.2.3 on 2020-04-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Filmmakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电影id')),
                ('douban_id', models.IntegerField(blank=True, null=True, verbose_name='豆瓣id')),
                ('movie_name', models.CharField(max_length=100, verbose_name='电影片名')),
                ('movie_length', models.CharField(blank=True, max_length=10, null=True, verbose_name='电影片长')),
                ('movie_year', models.CharField(max_length=4, verbose_name='电影年代')),
                ('movie_releaseTime', models.CharField(blank=True, max_length=12, null=True, verbose_name='上映时间')),
                ('movie_showPos', models.CharField(blank=True, max_length=10, null=True, verbose_name='上映地区')),
                ('movie_intro', models.TextField(blank=True, max_length=1024, null=True, verbose_name='剧情简介')),
                ('movie_cover', models.CharField(blank=True, max_length=150, null=True, verbose_name='电影封面图片路径')),
                ('movie_grades', models.FloatField(blank=True, default=0.0, null=True, verbose_name='豆瓣评分')),
                ('movie_alias', models.CharField(max_length=100, verbose_name='电影别名')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影标签id')),
                ('lab_content', models.CharField(max_length=50, verbose_name='电影标签内容')),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影类别id')),
                ('type_name', models.CharField(max_length=20, unique=True, verbose_name='电影类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', '导演'), ('actor', '演员')], max_length=15, verbose_name='在电影中的角色')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmmakers.Celebrity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024, verbose_name='评论内容')),
                ('author_name', models.CharField(max_length=50, verbose_name='评论作者')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='lab',
            field=models.ManyToManyField(blank=True, to='Movies.MovieLab'),
        ),
        migrations.AddField(
            model_name='movie',
            name='roles',
            field=models.ManyToManyField(through='Movies.RoleTable', to='Filmmakers.Celebrity'),
        ),
        migrations.AddField(
            model_name='movie',
            name='types',
            field=models.ManyToManyField(blank=True, to='Movies.MovieType'),
        ),
    ]
