# Generated by Django 2.2.3 on 2020-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电影片长'),
        ),
    ]
