# Generated by Django 2.2.3 on 2019-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_intro',
            field=models.CharField(max_length=512, null='true', verbose_name='剧情简介'),
            preserve_default='true',
        ),
    ]
