# Generated by Django 3.0.2 on 2020-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieCategory',
            new_name='MovieType',
        ),
        migrations.RenameField(
            model_name='movietype',
            old_name='category_id',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='movietype',
            old_name='category_name',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='types',
            field=models.ManyToManyField(to='Movies.MovieType'),
        ),
    ]
