# Generated by Django 2.2.3 on 2020-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20200401_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(default=111111, verbose_name='豆瓣id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='lab',
            field=models.ManyToManyField(blank=True, to='Movies.MovieLab'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_showPos',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='上映地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.ManyToManyField(blank=True, to='Movies.MovieType'),
        ),
    ]
