# Generated by Django 2.2.3 on 2020-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_auto_20200401_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cover',
            field=models.CharField(max_length=150, verbose_name='电影封面图片路径'),
        ),
    ]
