# Generated by Django 2.2.3 on 2020-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20200402_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=100, verbose_name='电影片名'),
        ),
    ]
