# Generated by Django 2.2.3 on 2020-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_auto_20200403_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='豆瓣id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_cover',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='电影封面图片路径'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_grades',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='豆瓣评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='电影id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_intro',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='剧情简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='电影片长'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_releaseTime',
            field=models.CharField(max_length=12, verbose_name='上映时间'),
        ),
    ]
